=== Cad-MB/BCM4Java_sensors/src/main/resources/configs/forest.dtd
<!ELEMENT forest (node)*>
        <!ELEMENT node (id,range,position,delay,sensors,inboundPorts,outboundPorts)>
        <!ELEMENT id (#PCDATA)>
        <!ELEMENT range (#PCDATA)>
        <!ELEMENT position EMPTY>
        <!ATTLIST position x CDATA #REQUIRED y CDATA #REQUIRED>
        <!ELEMENT delay (#PCDATA)>
        <!ELEMENT sensors (sensor)*>
        <!ELEMENT sensor EMPTY>
        <!ATTLIST sensor
                id CDATA #REQUIRED
                value CDATA #REQUIRED
                toAdd CDATA #REQUIRED>
        <!ELEMENT inboundPorts (port)*>
        <!ELEMENT outboundPorts (port)*>
        <!ELEMENT port EMPTY>
        <!ATTLIST port
                for CDATA #REQUIRED
                uri CDATA #REQUIRED>

=== Cad-MB/BCM4Java_sensors/src/main/resources/configs/large30/forest.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE forest SYSTEM "../forest.dtd" >
<forest>
    <!-- first column  -->
    <node>
        <id>1:1</id>
        <range>200</range>
        <position x="-200" y="400"/>
        <delay>4560</delay>
        <sensors>
            <sensor id="temp" value="20" toAdd="10"/>
            <sensor id="humidity" value="20" toAdd="1"/>
        </sensors>
        <inboundPorts>
            <port for="requesting" uri="1:1:in:requesting"/>
            <port for="p2p" uri="1:1:in:p2p"/>
        </inboundPorts>
        <outboundPorts>
            <port for="request-result" uri="1:1:out:request-result"/>
            <port for="p2p" uri="1:1:out:p2p"/>
            <port for="registration" uri="1:1:out:registration"/>
        </outboundPorts>
    </node>
    <node>
        <id>1:2</id>
        <range>200</range>
        <position x="-200" y="200"/>
        <delay>4680</delay>
        <sensors>
            <sensor id="temp" value="20" toAdd="5"/>
            <sensor id="humidity" value="20" toAdd="10"/>
        </sensors>
        <inboundPorts>
            <port for="requesting" uri="1:2:in:requesting"/>
            <port for="p2p" uri="1:2:in:p2p"/>
        </inboundPorts>
        <outboundPorts>
            <port for="request-result" uri="1:2:out:request-result"/>
            <port for="p2p" uri="1:2:out:p2p"/>
            <port for="registration" uri="1:2:out:registration"/>
        </outboundPorts>
    </node>
    <node>
        <id>1:3</id>
        <range>200</range>
        <position x="-200" y="0"/>
        <delay>4800</delay>
        <sensors>
            <sensor id="temp" value="20" toAdd="5"/>
            <sensor id="humidity" value="20" toAdd="1"/>
        </sensors>
        <inboundPorts>
            <port for="requesting" uri="1:3:in:requesting"/>
            <port for="p2p" uri="1:3:in:p2p"/>
        </inboundPorts>
        <outboundPorts>
            <port for="request-result" uri="1:3:out:request-result"/>
            <port for="p2p" uri="1:3:out:p2p"/>
            <port for="registration" uri="1:3:out:registration"/>
        </outboundPorts>
    </node>

    <!-- second column -->
    <node>
        <id>2:1</id>
        <range>200</range>
        <position x="-100" y="500"/>
        <delay>4500</delay>
        <sensors>
            <sensor id="temp" value="20" toAdd="2"/>
            <sensor id="humidity" value="20" toAdd="3"/>
        </sensors>
        <inboundPorts>
            <port for="requesting" uri="2:1:in:requesting"/>
            <port for="p2p" uri="2:1:in:p2p"/>
        </inboundPorts>
        <outboundPorts>
            <port for="request-result" uri="2:1:out:request-result"/>
            <port for="p2p" uri="2:1:out:p2p"/>
            <port for="registration" uri="2:1:out:registration"/>
        </outboundPorts>
    </node>
    <node>
        <id>2:2</id>
        <range>200</range>
        <position x="-100" y="300"/>
        <delay>4620</delay>
        <sensors>
            <sensor id="temp" value="20" toAdd="3"/>
            <sensor id="humidity" value="20" toAdd="4"/>
        </sensors>
        <inboundPorts>
            <port for="requesting" uri="2:2:in:requesting"/>
            <port for="p2p" uri="2:2:in:p2p"/>
        </inboundPorts>
        <outboundPorts>
            <port for="request-result" uri="2:2:out:request-result"/>
            <port for="p2p" uri="2:2:out:p2p"/>
            <port for="registration" uri="2:2:out:registration"/>
        </outboundPorts>
    </node>
    <node>
        <id>2:3</id>
        <range>200</range>
        <position x="-100" y="100"/>
        <delay>4740</delay>
        <sensors>
            <sensor id="temp" value="20" toAdd="5"/>
            <sensor id="humidity" value="20" toAdd="5"/>
        </sensors>
        <inboundPorts>
            <port for="requesting" uri="2:3:in:requesting"/>
            <port for="p2p" uri="2:3:in:p2p"/>
        </inboundPorts>
        <outboundPorts>
            <port for="request-result" uri="2:3:out:request-result"/>
            <port for="p2p" uri="2:3:out:p2p"/>
            <port for="registration" uri="2:3:out:registration"/>
        </outboundPorts>
    </node>

    <!--  third column  -->
    <node>
        <id>3:1</id>
        <range>200</range>
        <position x="0" y="400"/>
        <delay>4800</delay>
        <sensors>
            <sensor id="temp" value="20" toAdd="5"/>
            <sensor id="humidity" value="20" toAdd="9"/>
        </sensors>
        <inboundPorts>
            <port for="requesting" uri="3:1:in:requesting"/>
            <port for="p2p" uri="3:1:in:p2p"/>
        </inboundPorts>
        <outboundPorts>
            <port for="request-result" uri="3:1:out:request-result"/>
            <port for="p2p" uri="3:1:out:p2p"/>
            <port for="registration" uri="3:1:out:registration"/>
        </outboundPorts>
    </node>
    <node>
        <id>3:2</id>
        <range>200</range>
        <position x="0" y="200"/>
        <delay>4860</delay>
        <sensors>
            <sensor id="temp" value="20" toAdd="10"/>
            <sensor id="humidity" value="20" toAdd="11"/>
        </sensors>
        <inboundPorts>
            <port for="requesting" uri="3:2:in:requesting"/>
            <port for="p2p" uri="3:2:in:p2p"/>
        </inboundPorts>
        <outboundPorts>
            <port for="request-result" uri="3:2:out:request-result"/>
            <port for="p2p" uri="3:2:out:p2p"/>
            <port for="registration" uri="3:2:out:registration"/>
        </outboundPorts>
    </node>
    <node>
        <id>3:3</id>
        <range>200</range>
        <position x="0" y="0"/>
        <delay>4920</delay>
        <sensors>
            <sensor id="temp" value="20" toAdd="2"/>
            <sensor id="humidity" value="20" toAdd="9"/>
        </sensors>
        <inboundPorts>
            <port for="requesting" uri="3:3:in:requesting"/>
            <port for="p2p" uri="3:3:in:p2p"/>
        </inboundPorts>
        <outboundPorts>
            <port for="request-result" uri="3:3:out:request-result"/>
            <port for="p2p" uri="3:3:out:p2p"/>
            <port for="registration" uri="3:3:out:registration"/>
        </outboundPorts>
    </node>

    <!--  fourth column  -->
    <node>
        <id>4:1</id>
        <range>200</range>
        <position x="100" y="500"/>
        <delay>4000</delay>
        <sensors>
            <sensor id="temp" value="20" toAdd="12"/>
            <sensor id="humidity" value="20" toAdd="8"/>
        </sensors>
        <inboundPorts>
            <port for="requesting" uri="4:1:in:requesting"/>
            <port for="p2p" uri="4:1:in:p2p"/>
        </inboundPorts>
        <outboundPorts>
            <port for="request-result" uri="4:1:out:request-result"/>
            <port for="p2p" uri="4:1:out:p2p"/>
            <port for="registration" uri="4:1:out:registration"/>
        </outboundPorts>
    </node>
    <node>
        <id>4:2</id>
        <range>200</range>
        <position x="100" y="300"/>
        <delay>4500</delay>
        <sensors>
            <sensor id="temp" value="20" toAdd="5"/>
            <sensor id="humidity" value="20" toAdd="5"/>
        </sensors>
        <inboundPorts>
            <port for="requesting" uri="4:2:in:requesting"/>
            <port for="p2p" uri="4:2:in:p2p"/>
        </inboundPorts>
        <outboundPorts>
            <port for="request-result" uri="4:2:out:request-result"/>
            <port for="p2p" uri="4:2:out:p2p"/>
            <port for="registration" uri="4:2:out:registration"/>
        </outboundPorts>
    </node>
    <node>
        <id>4:3</id>
        <range>200</range>
        <position x="100" y="100"/>
        <delay>5000</delay>
        <sensors>
            <sensor id="temp" value="20" toAdd="5"/>
            <sensor id="humidity" value="20" toAdd="5"/>
        </sensors>
        <inboundPorts>
            <port for="requesting" uri="4:3:in:requesting"/>
            <port for="p2p" uri="4:3:in:p2p"/>
        </inboundPorts>
        <outboundPorts>
            <port for="request-result" uri="4:3:out:request-result"/>
            <port for="p2p" uri="4:3:out:p2p"/>
            <port for="registration" uri="4:3:out:registration"/>
        </outboundPorts>
    </node>

    <!--  fifth column  -->
    <node>
        <id>5:1</id>
        <range>200</range>
        <position x="200" y="400"/>
        <delay>5060</delay>
        <sensors>
            <sensor id="temp" value="20" toAdd="5"/>
            <sensor id="humidity" value="20" toAdd="5"/>
        </sensors>
        <inboundPorts>
            <port for="requesting" uri="5:1:in:requesting"/>
            <port for="p2p" uri="5:1:in:p2p"/>
        </inboundPorts>
        <outboundPorts>
            <port for="request-result" uri="5:1:out:request-result"/>
            <port for="p2p" uri="5:1:out:p2p"/>
            <port for="registration" uri="5:1:out:registration"/>
        </outboundPorts>
    </node>
    <node>
        <id>5:2</id>
        <range>200</range>
        <position x="200" y="200"/>
        <delay>5120</delay>
        <sensors>
            <sensor id="temp" value="20" toAdd="5"/>
            <sensor id="humidity" value="20" toAdd="5"/>
        </sensors>
        <inboundPorts>
            <port for="requesting" uri="5:2:in:requesting"/>
            <port for="p2p" uri="5:2:in:p2p"/>
        </inboundPorts>
        <outboundPorts>
            <port for="request-result" uri="5:2:out:request-result"/>
            <port for="p2p" uri="5:2:out:p2p"/>
            <port for="registration" uri="5:2:out:registration"/>
        </outboundPorts>
    </node>
    <node>
        <id>5:3</id>
        <range>200</range>
        <position x="200" y="0"/>
        <delay>5180</delay>
        <sensors>
            <sensor id="temp" value="20" toAdd="5"/>
            <sensor id="humidity" value="20" toAdd="5"/>
        </sensors>
        <inboundPorts>
            <port for="requesting" uri="5:3:in:requesting"/>
