=== Cad-MB/BCM4Java_sensors/src/main/resources/configs/tests.dtd
<!ELEMENT tests (test)*>
        <!ELEMENT test (name,clientId,requestId,afterDelay,isBoolean,(expectBoolean|expectGather))>
        <!ELEMENT name (#PCDATA)>
        <!ELEMENT clientId (#PCDATA)>
        <!ELEMENT requestId (#PCDATA)>
        <!ELEMENT afterDelay (#PCDATA)>
        <!ELEMENT isBoolean (#PCDATA)>
        <!ELEMENT expectBoolean (nodeId)*>
        <!ELEMENT nodeId (#PCDATA)>
        <!ELEMENT expectGather (sensor)*>
        <!ELEMENT sensor (#PCDATA)>
        <!ATTLIST sensor
                nodeId CDATA #REQUIRED
                sensorId CDATA #REQUIRED
                value CDATA #REQUIRED>

=== Cad-MB/BCM4Java_sensors/src/main/resources/configs/large30/tests.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE tests SYSTEM "../tests.dtd">
<tests>
    <executionTime></executionTime>
    <test>
        <name>test client 2</name>
        <clientId>client2</clientId>
        <requestId>client2-1</requestId>
        <afterDelay>550</afterDelay>
        <isBoolean>true</isBoolean>
        <expectBoolean>
            <nodeId>4:3</nodeId>
            <nodeId>5:2</nodeId>
        </expectBoolean>
    </test>
    <test>
        <name>test client 2 1</name>
        <clientId>client2</clientId>
        <requestId>client2-1</requestId>
        <afterDelay>551</afterDelay>
        <isBoolean>true</isBoolean>
        <expectBoolean>
            <nodeId>5:2</nodeId>
        </expectBoolean>
    </test>
</tests>

=== Cad-MB/BCM4Java_sensors/src/main/resources/configs/big6/tests.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE tests SYSTEM "../tests.dtd">
<tests>
    <executionDuration>200000</executionDuration>
    <test>
        <name>client1:test1</name>
        <clientId>client1</clientId>
        <requestId>client1-0</requestId>
        <afterDelay>60</afterDelay>
        <isBoolean>false</isBoolean>
        <expectGather>
            <sensor sensorId="" nodeId="" value="10"/>
            <sensor sensorId="" nodeId="" value="10"/>
        </expectGather>
    </test>
</tests>
